# Generated by Django 3.0.7 on 2020-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20200611_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=3)),
            ],
        ),
    ]
