# Generated by Django 3.0.7 on 2020-06-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20200611_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='feature',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
