# Generated by Django 3.0.7 on 2020-06-12 04:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_dog_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('homepage', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('rate', models.FloatField(blank=True, default=0)),
                ('userid', models.CharField(max_length=50)),
            ],
        ),
    ]
