# Generated by Django 3.0.7 on 2020-06-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
            ],
        ),
    ]
