# Generated by Django 3.0.7 on 2020-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_auto_20200611_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
