# Generated by Django 3.0.7 on 2020-06-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='hotels',
        ),
    ]
