# Generated by Django 3.0.7 on 2020-06-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200612_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
