# Generated by Django 3.0.7 on 2020-06-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200612_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='userid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
